### PR TITLE
Fix typescript declaration

### LINKED ISSUE #377: Typescript problems
Getting this with React-Markdown 4.3.0 and Typescript 3.7.4.

Not sure what additional detail I could help with here :/

```
ERROR in node_modules/react-markdown/index.d.ts
ERROR in node_modules/react-markdown/index.d.ts(138,16):
TS2665: Invalid module name in augmentation. Module 'react-markdown/with-html' resolves to an untyped module at 'node_modules/react-markdown/with-html.js', which cannot be augmented.

ERROR in node_modules/react-markdown/index.d.ts
ERROR in node_modules/react-markdown/index.d.ts(140,35):
TS2307: Cannot find module 'react-markdown'.
```

### PR DESCRIPTION
**Pull request by peng1999**
As @petersowa pointed out in https://github.com/rexxars/react-markdown/pull/352#pullrequestreview-337828385 , I made a mistake in #352 . This should fix the bug.

Fixes #377

### CODE REVIEW

File: with-html.d.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import {Component} from 'react'
+import ReactMarkdownRoot from 'react-markdown'
+
+export default class ReactMarkdown extends Component<ReactMarkdownRoot.ReactMarkdownProps, {}> {}
```
Comment (AviVahl) [inline with-html.d.ts]: the actual `with-html.js` file has commonjs export, so this line should probably be:
```ts
declare class ReactMarkdown extends Component<ReactMarkdownRoot.ReactMarkdownProps, {}> {};
export = ReactMarkdown;
```
could/should probably also change the import to:
```ts
import ReactMarkdownRoot = require('react-markdown');
```

This way, the `.d.ts` will be compatible with `esModuleInterop` on or off.

Comment (rexxars) [reply with-html.d.ts]: Thanks for the review @AviVahl :)
